import { Inter } from "next/font/google";
import "./globals.css";
import {PRDComponent} from "@/components/PRDComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html>
        <body>
          <PRDComponent/>
        </body>
      </html>

  );
}
