/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pepRT3KdcF5
 */
"use client";
import { useState } from 'react';
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import axios from 'axios';

// 使用 "use client" 注释来标记这个组件为客户端组件
// 导入的组件也应该是客户端组件
export function PRDComponent() {
    // 创建一个state来存储输入框的值
    const [inputValue, setInputValue] = useState('');
    const [documentContent, setDocumentContent] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const api_url = "http://127.0.0.1:5000/tdd_demo/prd_gen?idea="

    // 创建一个事件处理函数来响应按钮点击
    const handleButtonClick = async () => {
        setIsLoading(true);
        try {
            // const response = await axios.post(api_url, {
            //     data: inputValue, // 发送输入框的内容
            // });
            let final_api_url = api_url + inputValue
            const response = await axios.get(final_api_url);
            // 将响应的数据设置为文档内容
            setDocumentContent(response.data.PRDContent);
        } catch (error) {
            // 处理错误
            console.error(error);
        } finally {
            // 在请求完成后（无论成功还是失败），设置加载状态为false
            setIsLoading(false);
        }
    };

    // 更新输入框内容的事件处理函数
    const handleInputChange = (e) => {
        setInputValue(e.target.value);
    };

    const handleNextClick = (e) => {

    }

    return (
        <div key="1" className="flex flex-col h-screen">
            <header className="flex items-center justify-between p-4 bg-gray-800 text-white">
                <h1 className="text-2xl font-bold">PRD Generator</h1>
            </header>
            <main className="flex-1 overflow-auto p-4 bg-gray-100 dark:bg-gray-900">
                <Textarea
                    className="w-full h-full p-4 rounded-md bg-white shadow-md dark:bg-gray-800 dark:text-white"
                    placeholder="Your document will appear here..."
                    value={documentContent}
                    readOnly={true} />
            </main>
            <footer className="flex items-center justify-between p-4 bg-gray-800">
                <Input
                    className="flex-grow mr-4 p-2 rounded-md bg-white dark:bg-gray-800 dark:text-white"
                    placeholder="Enter your idea or question here..."
                    value={inputValue}
                    onChange={handleInputChange} />
                <Button
                    className="bg-blue-500 text-white rounded-md px-4 py-2"
                    disabled={isLoading} // 当isLoading为true时，按钮不可点击
                    onClick={handleButtonClick}>
                    Generate Document
                </Button>
                <Button className="bg-blue-500 text-white rounded-md px-4 py-2 ml-4"
                    onClick={handleNextClick}>
                    Next Page
                </Button>
            </footer>
        </div>
    );
}